version: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh  # Set múi giờ
      - N8N_BASIC_AUTH_ACTIVE=true         # Bật xác thực cơ bản
      - N8N_BASIC_AUTH_USER=admin          # Tên người dùng
      - N8N_BASIC_AUTH_PASSWORD=22022000   # Mật khẩu
      # - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false 
    volumes:
      - ./n8n_data:/home/node/.n8n         # Lưu dữ liệu cục bộ
