  version: "3.9"

  services:
    n8n:
      image: n8nio/n8n:latest
      container_name: n8n
      ports:
        - "5678:5678"
      env_file:
        - .env
      volumes:
        - ./n8n_data:/home/node/.n8n
