version: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_USER_MANAGEMENT_DISABLED=false   
      - N8N_AUTH_EXCLUDE_ENDPOINTS=          
      - N8N_ADMIN_EMAIL=thangmk7@gmail.com  
      - N8N_ADMIN_PASSWORD=t22022000
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n       
